/* Shared animal data. Loaded before quiz.js and pokedex.js.
   Top-level const in a classic script is visible to later scripts;
   window.ANIMALS is set as well so anything can reach it safely. */

// Bonus cards are field-guide discoveries, never personality-quiz outcomes.
const QUIZ_ANIMAL_KEYS = ['otter', 'dhole', 'loris', 'pangolin', 'fishingcat', 'tiger', 'binturong'];

// Each animal mirrors the Veggie ID card: strengths, weakness, quotes, alignment, hidden talent, peer reviews.
const ANIMALS = {
  otter: {
    name: 'Asian Small-clawed Otter', color: '#e9a35c',
    tagline: 'Smallest otter in the world, loudest otter in the room',
    strengths: ['Makes friends in under four seconds', 'Catches its snacks in its hands, like a very small person', 'Genuinely excited about snacks, every single time'],
    weakness: ['Volume control is theoretical', 'Cannot pass a body of water without commentary', 'Will befriend the tram guide and forget the tram'],
    quotes: ['"Wait wait wait, look at THAT"', '"Okay but are we getting dessert though"'],
    alignment: 'Lawful 30%, Neutral 20%, Chaotic 50%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Can turn any queue into a friend group',
    peers: [['Otter once cheered so loudly for me that I forgot to be shy.', 'Pangolin'], ['Splashed me. Said sorry. Splashed me again.', 'Fishing Cat']],
    fact: 'The smallest otter in the world. Its claws are so short and its fingers so nimble that it picks food up in its hands instead of its mouth.',
    findme: 'Pangolin Trail',
    compat: [98, "An otter and a fishing cat, which is to say two animals that refuse to stay out of the water. You would swim for the joy of it. I would come back holding dinner."],
  },
  dhole: {
    name: 'Dhole (Asian Wild Dog)', color: '#e88a4c',
    tagline: 'The golden retriever of the jungle. This is peer-reviewed.',
    strengths: ["Greets everyone like they've been gone for years", 'Whistles instead of barking to find its friends in the dark', 'Loyal to a level that concerns biologists'],
    weakness: ['Has never once said no to a plan', 'Runs toward things before knowing what they are', "Thinks 'we should all hang out' is a full sentence"],
    quotes: ['"This is going to be SO fun" (it was)', '"I\'m not lost, I\'m exploring with confidence"'],
    alignment: 'Lawful 60%, Neutral 25%, Chaotic 15%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: "Remembers the name of every dog they've ever met. Owners, less so.",
    peers: [['Dhole ran across the whole park to bring me a snack I mentioned once. Once.', 'Slow Loris'], ['Whistled at me for ten minutes. I think it was a compliment.', 'Tiger']],
    fact: 'Dhole packs let the pups eat first at a kill, which is the exact opposite of how a wolf pack does it.',
    findme: 'Seen from the tram',
    compat: [97, 'You greet the entire tram. I quietly case the place for the best supper stall. Between us we would survive any jungle and every hawker centre.'],
  },
  loris: {
    name: 'Sunda Slow Loris', color: '#c9ad83',
    tagline: 'Big eyes, zero rush, secretly venomous (only if provoked)',
    strengths: ['Notices everything, mentions it later', 'Calm in a way that calms other people', 'Arrives late and somehow exactly on time'],
    weakness: ["'Five more minutes' is a lifestyle", 'Needs four minutes to choose a drink and will not be rushed on this', 'Cannot be hurried. Has been tested.'],
    quotes: ['"I\'m coming, I\'m coming" (was not coming)', '"Wait, did you see that? No? Too late."'],
    alignment: 'Lawful 55%, Neutral 40%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Finds the one comfortable spot in any room within a minute',
    peers: [['Loris listened to me talk for an hour and remembered all of it.', 'Otter'], ['I watched them consider a leaf for four minutes. Respect.', 'Binturong']],
    fact: 'One of the only venomous primates on Earth. It licks a gland inside its own elbow and mixes the oil with its saliva.',
    findme: 'Pangolin Trail',
    compat: [96, 'The slowest animal on the trail and the most patient one. A fishing cat can sit at the water for an hour without blinking, so genuinely, take your time.'],
  },
  pangolin: {
    name: 'Sunda Pangolin', color: '#d9b26a',
    tagline: 'Armoured outside, complete softie inside (also: not a hedgehog)',
    strengths: ['Quietly the most caring one in the room', 'Unbothered by drama, is wearing armour', 'Will absolutely show up if you need them'],
    weakness: ['Curls into a ball when a group photo is suggested', 'Takes a while to open up, then never stops', 'Has researched the tram timings, will not admit it'],
    quotes: ['"I\'m fine" (is thinking about it)', '"Oh, I actually read about this..."'],
    alignment: 'Lawful 75%, Neutral 20%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Remembers the small thing you said three weeks ago',
    peers: [["Pangolin doesn't say much but somehow always has a plaster when I need one.", 'Dhole'], ['Rolled into a ball when I complimented them. Adorable. Concerning.', 'Otter']],
    fact: "A pangolin pup rides around on the base of its mother's tail, and gets tucked safely inside when she curls into a ball.",
    findme: 'Pangolin Trail',
    compat: [97, 'You are armoured and I am waterproof. Between the scales and the swimming, very little can go wrong on Saturday.'],
  },
  fishingcat: {
    name: 'Fishing Cat', color: '#a9b39a',
    tagline: 'The cat that read the rules about water and said no',
    strengths: ['Independent, a little mysterious, unexpectedly good at things', "Patient right up until it's time to pounce", 'Cool under pressure, warm under everything else'],
    weakness: ["'I'll just do it myself' about literally everything", 'Has strong opinions about the correct snack', 'Will pause a conversation mid-sentence for a good otter sighting'],
    quotes: ['"I didn\'t plan it, it just worked out" (planned it)', '"Hm. Interesting." (very interested)'],
    alignment: 'Lawful 40%, Neutral 45%, Chaotic 15%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Finds the best food stall within 200 metres of anywhere',
    peers: [['Fishing Cat caught dinner in the time it took me to open the menu. Did not even look smug about it.', 'Slow Loris'], ['Caught a fish in front of me. Made eye contact. Ate it.', 'Otter']],
    fact: 'A cat that dives. It swims underwater and has been seen snatching waterbirds from below the surface.',
    findme: 'Pangolin Trail',
    compat: [99, 'Two fishing cats. Both independent, both quietly delighted, both insisting we did not plan this. We absolutely planned this.'],
  },
  tiger: {
    name: 'Malayan Tiger', color: '#f0973a',
    tagline: 'Main character energy, respectfully',
    strengths: ['Walks in, room rearranges itself', 'Fiercely protective of their people', "Warm immediately, but somehow you still feel like you got the good seat"],
    weakness: ['Sleeps sixteen hours a day if unsupervised', 'Has The Look. Uses it.', 'Will renegotiate a bad plan in real time, mid-plan'],
    quotes: ['"I\'m not competitive" (is very competitive)', '"Okay, fine, that\'s actually cute"'],
    alignment: 'Lawful 50%, Neutral 20%, Chaotic 30%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Photographs well from every angle, including asleep',
    peers: [["Tiger scared off someone who cut the queue for me. Didn't say anything. Just looked.", 'Pangolin'], ['Napped through my entire story. Woke up. Asked good follow-up questions.', 'Dhole']],
    fact: 'No two tigers wear the same stripes. Not even the left and right sides of the same tiger match.',
    findme: 'Seen from the tram',
    compat: [98, 'The largest cat in the park and one of the smallest. Same family, same unblinking stare, wildly different opinions about swimming.'],
  },
  binturong: {
    name: 'Binturong (Bearcat)', color: '#a898a0',
    tagline: 'Smells like buttered popcorn. This is real science.',
    strengths: ['Impossible to dislike, nobody can explain why', 'Chill to a degree that lowers nearby heart rates', 'Prehensile tail, which is honestly showing off'],
    weakness: ['Has fallen asleep mid-sentence, twice', 'Smells like a cinema at 2pm on a Tuesday. Never explains why.', "Cannot pass a snack without a 'small taste'"],
    quotes: ['"Wait, does anyone else smell popcorn?"', '"I\'m awake" (was not awake)'],
    alignment: 'Lawful 35%, Neutral 55%, Chaotic 10%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Can nap in any position, on any surface, at any brightness',
    peers: [['Binturong hugged me once and I smelled like a cinema for a week. Ten out of ten.', 'Otter'], ['Once watched them fall asleep standing up. I timed it. Forty seconds.', 'Slow Loris']],
    fact: 'Binturongs really do smell of hot buttered popcorn. Scientists tested 33 of them and found the exact compound that makes popcorn smell like popcorn. Nobody knows how they make it.',
    findme: 'Pangolin Trail',
    compat: [96, 'You smell of hot popcorn and I know exactly where the good supper is. Between us that is a complete evening.'],
  },
  tapir: {
    name: 'Malayan Tapir', color: '#b8beca', bonus: 'shadow',
    tagline: 'Dressed formally. Absolutely no plans.',
    strengths: ['Makes a quiet evening feel like the correct decision', 'Always leaves room on the picnic blanket', 'Excellent company for doing very little'],
    weakness: ['Mistakes a comfortable pause for the end of the itinerary', 'Has never hurried towards anything that was not lunch'],
    quotes: ['"We could just stay here a bit."', '"I brought leaves. Was this not a picnic?"'],
    alignment: 'Lawful 30%, Neutral 65%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Makes slowing down feel like something you planned',
    peers: [['Tapir saved me the shady spot. Did not make a big thing of it.', 'Pangolin'], ['I suggested five activities. Tapir suggested sitting down. Tapir won.', 'Otter']],
    fact: 'That black-and-white coat helps break up its outline in the dark. A tapir’s flexible little snout can bring food to its mouth and even act as a snorkel.',
    findme: 'Look out from the Safari Adventure Tram. Sightings are never guaranteed.',
  },
  flyingsquirrel: {
    name: 'Spotted Giant Flying Squirrel', color: '#d9ac7e', bonus: 'shadow',
    tagline: 'Said “follow me” before checking where.',
    strengths: ['Finds the scenic route even between two trees', 'Makes an ordinary detour feel like an expedition', 'Brings enough enthusiasm for the quieter friend too'],
    weakness: ['Calls every route a shortcut', 'Says “nearly there” from a different tree'],
    quotes: ['"I have an idea." (already airborne)', '"Technically, we are still on the way."'],
    alignment: 'Lawful 15%, Neutral 25%, Chaotic 60%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Turns getting slightly sidetracked into the best part of the evening',
    peers: [['We took a detour. It was a very good detour. I have no notes.', 'Dhole'], ['Offered me a shortcut. I offered to meet them on the ground.', 'Slow Loris']],
    fact: 'It glides rather than flying like a bird. A skin membrane called the patagium stretches between its limbs to carry it from tree to tree.',
    findme: 'Pangolin Trail. Look above you as well as ahead, and give it time.',
  },
  flyingfox: {
    name: 'Malayan Flying Fox', color: '#b89bbd', bonus: 'shadow',
    tagline: 'Looks mysterious. Is thinking about mangoes.',
    strengths: ['Turns up for the late-night snack run', 'Can make a quiet corner feel cosy', 'Takes fruit selection extremely seriously'],
    weakness: ['Looks dramatic while doing something completely ordinary', 'Has opinions about when a mango is ready'],
    quotes: ['"It is not a cape. These are my arms."', '"I am listening. I am also thinking about fruit."'],
    alignment: 'Lawful 35%, Neutral 50%, Chaotic 15%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Makes bringing a snack look like a mysterious entrance',
    peers: [['We had different ideas about supper. We both brought extra.', 'Fishing Cat'], ['Wore their wings like a blanket. I felt understood.', 'Binturong']],
    fact: 'A fruit bat, not a fox. Its keen sight and sense of smell help it find fruit and flowers at night, and it helps forests by spreading seeds and pollinating plants.',
    findme: 'Flying Fox Walkthrough on the Leopard Trail. Watch quietly and let the bats pass.',
  },
  owl: {
    name: 'Buffy Fish-owl', color: '#d9bd8c', bonus: 'shadow',
    tagline: 'Looks wise. The map is upside down.',
    strengths: ['Makes getting a little lost feel like a shared adventure', 'Notices the quiet things everyone else walks past', 'Always checks that you are still beside them'],
    weakness: ['Has confused north with a very convincing tree', 'Says “I recognise this bit” about every bit'],
    quotes: ['"We are exactly where I thought we might be."', '"The map is fine. It is the path that is upside down."'],
    alignment: 'Lawful 55%, Neutral 35%, Chaotic 10%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Turns the wrong turn into a story you will both keep telling',
    peers: [['We passed the same tree twice. I liked it both times.', 'Tapir'], ['Finally, someone else who understands the scenic route.', 'Flying Squirrel']],
    fact: 'Fish are a big part of its menu, but this owl also eats crabs, shrimp and frogs. A fish-owl’s supper is more varied than its name suggests.',
    findme: 'Pangolin Trail. Take your time looking up as well as along the path.',
  },
  porcupine: {
    name: 'Brazilian Porcupine', color: '#b7c8a3', bonus: 'shadow',
    tagline: 'Brought you a flower. Rehearsed this bit.',
    strengths: ['Remembers the little things you mentioned once', 'Shows up with something thoughtful in a tiny bag', 'Very good at quietly being on your side'],
    weakness: ['Has practised saying “this is for you” seven times', 'Needs a moment to warm up, then does not want to leave'],
    quotes: ['"Oh, this? I thought you might like it."', '"I was not nervous. I was adjusting my bag."'],
    alignment: 'Lawful 45%, Neutral 50%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Makes a very small gesture feel like the nicest part of the night',
    peers: [['The flower was lovely. So was the little speech before it.', 'Otter'], ['We sat quietly together. Excellent conversation.', 'Pangolin']],
    fact: 'Its long, prehensile tail can grip branches and help it climb. The tail can be about as long as the rest of its body.',
    findme: 'Pangolin Trail. Look among the branches, not just at ground level.',
  },
  elephant: {
    name: 'Asian Elephant', color: '#b9c6d2', bonus: 'shadow',
    tagline: 'Packed snacks. Remembered there are two of us.',
    strengths: ['Always brings enough to share', 'Makes sure nobody has to ask for the last snack', 'Makes you feel looked after without making a fuss'],
    weakness: ['A “small picnic” needs its own basket', 'Will ask if you have eaten even while you are eating'],
    quotes: ['"One for you. One for me."', '"I brought extra. Just in case the evening gets longer."'],
    alignment: 'Lawful 60%, Neutral 35%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Turns “shall we keep walking?” into a fully catered expedition',
    peers: [['Two parcels. Both excellent. No further questions.', 'Flying Fox'], ['Somebody else who respects the importance of a snack break.', 'Binturong']],
    fact: 'Wild elephants can spend up to 19 hours a day feeding on plants. That is a very long snack break, even by this group’s standards.',
    findme: 'Look out from the Safari Adventure Tram. A quiet, patient look is always worth it.',
  },
};

if (typeof window !== 'undefined') {
  window.ANIMALS = ANIMALS;
  window.QUIZ_ANIMAL_KEYS = QUIZ_ANIMAL_KEYS;
}
