/* Shared animal data. Loaded before quiz.js and pokedex.js.
   Top-level const in a classic script is visible to later scripts;
   window.ANIMALS is set as well so anything can reach it safely. */

// Each animal mirrors the Veggie ID card: strengths, weakness, quotes, alignment, hidden talent, peer reviews.
const ANIMALS = {
  otter: {
    name: 'Asian Small-clawed Otter', color: '#e9a35c',
    tagline: 'Smallest otter in the world, loudest otter in the room',
    strengths: ['Makes friends in under four seconds', 'Catches its snacks in its hands, like a very small person', 'Genuinely excited about snacks, every single time'],
    weakness: ['Volume control is theoretical', 'Cannot pass a body of water without commentary', 'Will befriend the tram guide and forget the tram'],
    quotes: ['"Wait wait wait, look at THAT"', '"Okay but are we getting dessert though"'],
    alignment: 'Lawful 30%, Neutral 20%, Chaotic 50%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Can turn any queue into a friend group',
    peers: [['Otter once cheered so loudly for me that I forgot to be shy.', 'Pangolin'], ['Splashed me. Said sorry. Splashed me again.', 'Fishing Cat']],
    fact: 'The smallest otter in the world. Its claws are so short and its fingers so nimble that it picks food up in its hands instead of its mouth.',
    findme: 'Pangolin Trail',
    compat: [98, "An otter and a fishing cat, which is to say two animals that refuse to stay out of the water. You would swim for the joy of it. I would come back holding dinner."],
  },
  dhole: {
    name: 'Dhole (Asian Wild Dog)', color: '#e88a4c',
    tagline: 'The golden retriever of the jungle. This is peer-reviewed.',
    strengths: ["Greets everyone like they've been gone for years", 'Whistles instead of barking to find its friends in the dark', 'Loyal to a level that concerns biologists'],
    weakness: ['Has never once said no to a plan', 'Runs toward things before knowing what they are', "Thinks 'we should all hang out' is a full sentence"],
    quotes: ['"This is going to be SO fun" (it was)', '"I\'m not lost, I\'m exploring with confidence"'],
    alignment: 'Lawful 60%, Neutral 25%, Chaotic 15%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: "Remembers the name of every dog they've ever met. Owners, less so.",
    peers: [['Dhole ran across the whole park to bring me a snack I mentioned once. Once.', 'Slow Loris'], ['Whistled at me for ten minutes. I think it was a compliment.', 'Tiger']],
    fact: 'Dhole packs let the pups eat first at a kill, which is the exact opposite of how a wolf pack does it.',
    findme: 'Seen from the tram',
    compat: [97, 'You greet the entire tram. I quietly case the place for the best supper stall. Between us we would survive any jungle and every hawker centre.'],
  },
  loris: {
    name: 'Sunda Slow Loris', color: '#c9ad83',
    tagline: 'Big eyes, zero rush, secretly venomous (only if provoked)',
    strengths: ['Notices everything, mentions it later', 'Calm in a way that calms other people', 'Arrives late and somehow exactly on time'],
    weakness: ["'Five more minutes' is a lifestyle", 'Needs four minutes to choose a drink and will not be rushed on this', 'Cannot be hurried. Has been tested.'],
    quotes: ['"I\'m coming, I\'m coming" (was not coming)', '"Wait, did you see that? No? Too late."'],
    alignment: 'Lawful 55%, Neutral 40%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Finds the one comfortable spot in any room within a minute',
    peers: [['Loris listened to me talk for an hour and remembered all of it.', 'Otter'], ['I watched them consider a leaf for four minutes. Respect.', 'Binturong']],
    fact: 'One of the only venomous primates on Earth. It licks a gland inside its own elbow and mixes the oil with its saliva.',
    findme: 'Pangolin Trail',
    compat: [96, 'The slowest animal on the trail and the most patient one. A fishing cat can sit at the water for an hour without blinking, so genuinely, take your time.'],
  },
  pangolin: {
    name: 'Sunda Pangolin', color: '#d9b26a',
    tagline: 'Armoured outside, complete softie inside (also: not a hedgehog)',
    strengths: ['Quietly the most caring one in the room', 'Unbothered by drama, is wearing armour', 'Will absolutely show up if you need them'],
    weakness: ['Curls into a ball when a group photo is suggested', 'Takes a while to open up, then never stops', 'Has researched the tram timings, will not admit it'],
    quotes: ['"I\'m fine" (is thinking about it)', '"Oh, I actually read about this..."'],
    alignment: 'Lawful 75%, Neutral 20%, Chaotic 5%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Remembers the small thing you said three weeks ago',
    peers: [["Pangolin doesn't say much but somehow always has a plaster when I need one.", 'Dhole'], ['Rolled into a ball when I complimented them. Adorable. Concerning.', 'Otter']],
    fact: "A pangolin pup rides around on the base of its mother's tail, and gets tucked safely inside when she curls into a ball.",
    findme: 'Pangolin Trail',
    compat: [97, 'You are armoured and I am waterproof. Between the scales and the swimming, very little can go wrong on Saturday.'],
  },
  fishingcat: {
    name: 'Fishing Cat', color: '#a9b39a',
    tagline: 'The cat that read the rules about water and said no',
    strengths: ['Independent, a little mysterious, unexpectedly good at things', "Patient right up until it's time to pounce", 'Cool under pressure, warm under everything else'],
    weakness: ["'I'll just do it myself' about literally everything", 'Has strong opinions about the correct snack', 'Will pause a conversation mid-sentence for a good otter sighting'],
    quotes: ['"I didn\'t plan it, it just worked out" (planned it)', '"Hm. Interesting." (very interested)'],
    alignment: 'Lawful 40%, Neutral 45%, Chaotic 15%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Finds the best food stall within 200 metres of anywhere',
    peers: [['Fishing Cat caught dinner in the time it took me to open the menu. Did not even look smug about it.', 'Slow Loris'], ['Caught a fish in front of me. Made eye contact. Ate it.', 'Otter']],
    fact: 'A cat that dives. It swims underwater and has been seen snatching waterbirds from below the surface.',
    findme: 'Pangolin Trail',
    compat: [99, 'Two fishing cats. Both independent, both quietly delighted, both insisting we did not plan this. We absolutely planned this.'],
  },
  tiger: {
    name: 'Malayan Tiger', color: '#f0973a',
    tagline: 'Main character energy, respectfully',
    strengths: ['Walks in, room rearranges itself', 'Fiercely protective of their people', "Warm immediately, but somehow you still feel like you got the good seat"],
    weakness: ['Sleeps sixteen hours a day if unsupervised', 'Has The Look. Uses it.', 'Will renegotiate a bad plan in real time, mid-plan'],
    quotes: ['"I\'m not competitive" (is very competitive)', '"Okay, fine, that\'s actually cute"'],
    alignment: 'Lawful 50%, Neutral 20%, Chaotic 30%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Photographs well from every angle, including asleep',
    peers: [["Tiger scared off someone who cut the queue for me. Didn't say anything. Just looked.", 'Pangolin'], ['Napped through my entire story. Woke up. Asked good follow-up questions.', 'Dhole']],
    fact: 'No two tigers wear the same stripes. Not even the left and right sides of the same tiger match.',
    findme: 'Seen from the tram',
    compat: [98, 'The largest cat in the park and one of the smallest. Same family, same unblinking stare, wildly different opinions about swimming.'],
  },
  binturong: {
    name: 'Binturong (Bearcat)', color: '#a898a0',
    tagline: 'Smells like buttered popcorn. This is real science.',
    strengths: ['Impossible to dislike, nobody can explain why', 'Chill to a degree that lowers nearby heart rates', 'Prehensile tail, which is honestly showing off'],
    weakness: ['Has fallen asleep mid-sentence, twice', 'Smells like a cinema at 2pm on a Tuesday. Never explains why.', "Cannot pass a snack without a 'small taste'"],
    quotes: ['"Wait, does anyone else smell popcorn?"', '"I\'m awake" (was not awake)'],
    alignment: 'Lawful 35%, Neutral 55%, Chaotic 10%<br>Good 100%, Neutral 0%, Evil 0%',
    talent: 'Can nap in any position, on any surface, at any brightness',
    peers: [['Binturong hugged me once and I smelled like a cinema for a week. Ten out of ten.', 'Otter'], ['Once watched them fall asleep standing up. I timed it. Forty seconds.', 'Slow Loris']],
    fact: 'Binturongs really do smell of hot buttered popcorn. Scientists tested 33 of them and found the exact compound that makes popcorn smell like popcorn. Nobody knows how they make it.',
    findme: 'Pangolin Trail',
    compat: [96, 'You smell of hot popcorn and I know exactly where the good supper is. Between us that is a complete evening.'],
  },
};

if (typeof window !== 'undefined') window.ANIMALS = ANIMALS;
